source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '10.0'

target 'LYLoading_Example' do
  pod 'LYLoading', :path => '../'

  target 'LYLoading_Tests' do
    inherit! :search_paths

    
  end
end


post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
    end
end